<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CsvMetricsProcessorService.Application\CsvMetricsProcessorService.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CsvHelper" Version="33.1.0" />
      <PackageReference Include="Dapper" Version="2.1.79" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.16" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

</Project>
