FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/CsvMetricsProcessorService.API/CsvMetricsProcessorService.API.csproj", "src/CsvMetricsProcessorService.API/"]
RUN dotnet restore "src/CsvMetricsProcessorService.API/CsvMetricsProcessorService.API.csproj"
COPY . .
WORKDIR "/src/src/CsvMetricsProcessorService.API"
RUN dotnet build "./CsvMetricsProcessorService.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./CsvMetricsProcessorService.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CsvMetricsProcessorService.API.dll"]
