<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CsvMetricsProcessorService.Domain\CsvMetricsProcessorService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.2.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
    </ItemGroup>

</Project>
